services:
  - type: web
    name: futureal
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*.css
        name: Content-Type
        value: text/css; charset=utf-8
      - path: /*.js
        name: Content-Type
        value: application/javascript; charset=utf-8
      - path: /assets/*.css
        name: Content-Type
        value: text/css; charset=utf-8
      - path: /assets/*.js
        name: Content-Type
        value: application/javascript; charset=utf-8
    routes:
      - type: rewrite
        source: /assets/*
        destination: /assets/:splat
      - type: rewrite
        source: /*.png
        destination: /:file
      - type: rewrite
        source: /*.jpg
        destination: /:file
      - type: rewrite
        source: /*.jpeg
        destination: /:file
      - type: rewrite
        source: /*.gif
        destination: /:file
      - type: rewrite
        source: /*.svg
        destination: /:file
      - type: rewrite
        source: /*.webp
        destination: /:file
      - type: rewrite
        source: /*.avif
        destination: /:file
      - type: rewrite
        source: /*.mp4
        destination: /:file
      - type: rewrite
        source: /*.webm
        destination: /:file
      - type: rewrite
        source: /*
        destination: /index.html
